name: "Exam 8 Notes"
description: "CAS Exam 8 Notes"

baseurl: /Exam-8-2015-Notes

paginate: 40

markdown: rdiscount
permalink: pretty
highlighter: rouge
github: [Repository metadata]

gems: [jekyll-paginate]
