---
title: "TIA Exams"
author: "TIA"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 4
---

## Exam 2015

### Q1

Know how the experience rating ties in with the 3 risk classification principles

### Q2

For GLM know how the error distribution affect the fit

* Higher variance function gets less weight for the higher values

### Q3

Know how it all fits with like Merit and Territory rating

* Still not 100% sure, lots of arithemtics

### Q4

You can just straight weight the $R(L)$ for different injury types here

* Doesn't even have to normalize

Do XS ratio under entry ratio is just to normalize the mean

### Q5

Straight forward quintile test from multi cred proc

### Q6

Calculate net charge based on lee diagram for Table L charge

### Q7

Get the retro premium at adjustment with LLM table

### Q8

Purpose of Table L

NCCI solution to the occ/agg overlap

Pros and cons for table L and ICRLL

### Q9

Standard Table L Lookup

### Q10

For 2 years of inflation you have to do it 1 year at a time

* Not as striaght forward as it first seems

Consistency test after inflation proof

* Need to know what the first 2 order of differential is for ILF

### Q11

XS ratio only relies on the severity distribution

Know the $R(L)$ formula as well as the dispersion formula

### Q12

Standard truncate and shift question

### Q13

Off balance explanation on increasing rate adequacy

### Q14

Exp mod quintile test

### Q15

Fullblown NCCI experience rating

* Note that disease and multi claim limits are looked at seperately

### Q16

Get AER, for CM so not development

### Q17

The ex med formula...

* Doesn't have to memorize just know that what varies and what doesn't and you can back it out

And why not all of med is reduced

### Q18

Build table M

Part b should probably have a way to simplify...

Know what happens when the \# of risk increase

### Q19

k is the ELPPF

Look up table 4B for ELG

This is for the XS losses in the LDD

### Q20

Cat model modules

### Q21

Recursive freq and sev

With sliding scale commission

### Q22

Inuring treaty refers to ground-up loss, and the 2nd treaty refers to loss net of the first treaty

Mix of exposure and experience rating

## Exam 2014

### Q1

List out 3 potential issues under all classification criteria

### Q2

Aliasing

Only when it's a lin comb between explanatory variables

### Q3

Lots of arithemtic and also needs to know how to get R with a distribution

### Q4

support for experience rating

### Q5

Support for adjustments to the data before getting $R(L)$

### Q6

Summary of the multi dimension credibility proc

### Q7

Table M, don't forget to aggregate losses on a policy level

### Q8

Draw lee diagram

### Q9

Back out from GCP for Retro

### Q10

Standard Table Lookup questions

Make sure we're applying the XS Ratio appropriately

### Q11

Know the charge relationship plots when premium size increase

Pretty difficult charge question

### Q12

Simply ILF and change in % losses

### Q13

XS Ratio in chunks and dispersion

### Q14

Off balance calca and also explanation of what it is

### Q15

Multiple class code lookup for experience rating

### Q16

Testing plan for one of the NCCI changes

### Q17

ISO Experience rating

For development portion of the AER, use the date from policy inception to evaluation date

### Q18

Simple LDD with explanation

### Q19

Simple charge lookup, need to use the right LER

### Q20

Cat model modules

### Q21

Retro calc with the swing plan

## Exam 2013

### Q6

k mean

### Q8

Consistency test and adverse selection

### Q9

Problem with standard loss development


### Q10

Truncate shift

### Q11

Impact of limiting losses

### Q13

Dorwieller and Off balance

### Q16

ISO Exp

### Q17

NCCI Experience, make sure we don't use ALAE

### Q18

unbalanced Retro

### Q19

LDD

### Q20

Retro

### Q21

All the open issues with cat model with details on actuarial acceptance

### Q22

Exposure curve conditions